/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import HammerMgr from "./manger/HammerMgr"
import GameMouseLayer from "./layer/GameMouseLayer"
import GameScene from "./scene/GameScene"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=1136;
    static height:number=640;
    static scaleMode:string="fixedwidth";
    static screenMode:string="horizontal";
    static alignV:string="middle";
    static alignH:string="center";
    static startScene:any="Scene/GameMain.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("manger/HammerMgr.ts",HammerMgr);
        reg("layer/GameMouseLayer.ts",GameMouseLayer);
        reg("scene/GameScene.ts",GameScene);
    }
}
GameConfig.init();